### ISSUE TITLE
Mod dosen't work in gt newhorizons(1.7.10 GTNH2.6.0 JAVA17)

### ISSUE THREAD

**Issue by shaqian150** [seanld03/RawInputMod-1.12.2-1.7.10#8]
In game can not move Mouse cursor. 
even if use /rescan still can not move.
PrsimLauncher ver8.3 MCGame ver1.7.10 GTNH ver2.6.0(JAVA17) JAVA17 ver17.0.10

**Comment by shaqian150** [comment]
and my mouse is RAZER DEATHADDER V3PRO 1000HZ

**Comment by shaqian150** [comment]
now in GTNH2.6.0 JAVA17ver. Lwjgl3ify comes with rawinput.
just in config folder open lwjgl3ify.cfg and find rawinput open it.

**Comment by Xiarno** [comment]
> now in GTNH2.6.0 JAVA17ver. Lwjgl3ify comes with rawinput. just in config folder open lwjgl3ify.cfg and find rawinput open it.

It does? Where exactly? Because I have this in my lwjgl3ify.cfg file:

![Image](https://github.com/user-attachments/assets/65d7689e-14e9-485e-a91d-736495fef204)

**Comment by glektarssza** [comment]
@Xiarno According to GTNewHorizons/lwjgl3ify#129 it does.

Glancing at the `lwjglify` source code, specifically [Config.java#L182](https://github.com/GTNewHorizons/lwjgl3ify/blob/master/src/main/java/me/eigenraven/lwjgl3ify/core/Config.java#L182), the config option is called `rawMouseInput` and should be placed in the `input` category like so:

```
#<TRUNCATED>

input {
    #<TRUNCATED>

    # Use raw (unaccelerated) mouse input [default: false]
    B:rawMouseInput=true

    #<TRUNCATED>
}

#<TRUNCATED>
```

Hope this helps!

**Comment by Xiarno** [comment]
> [@Xiarno](https://github.com/Xiarno) According to [GTNewHorizons/lwjgl3ify#129](https://github.com/GTNewHorizons/lwjgl3ify/issues/129) it does.
> 
> Glancing at the `lwjglify` source code, specifically [Config.java#L182](https://github.com/GTNewHorizons/lwjgl3ify/blob/master/src/main/java/me/eigenraven/lwjgl3ify/core/Config.java#L182), the config option is called `rawMouseInput` and should be placed in the `input` category like so:
> 
> ```
> #<TRUNCATED>
> 
> input {
>     #<TRUNCATED>
> 
>     # Use raw (unaccelerated) mouse input [default: false]
>     B:rawMouseInput=true
> 
>     #<TRUNCATED>
> }
> 
> #<TRUNCATED>
> ```
> 
> Hope this helps!

Yeah thanks! What happened is I downloaded the modpack from Prism Launcher. Everything seemed well and I could connect to servers fine. But after seeing so many time exactly what you describe to me and having none of that, I decided to take a closer look at the mod list. Turns out, downloading from Prism Launcher (Or I guess from Curseforge more precisely) has some missing mods, including lwjglify. I don't know what other mods are missing but from there I tried just downloading the same version of lwjglify that was supposed to be in and adding it to the modpack. It asked me for some extra configurations when launching that I never managed to setup so at this point I just downloaded the modpack instance straight from the GTNH Discord and imported it into Prism Launcher. No missing mods this time and I correctly had the config.
